$ANSIBLE_VAULT;1.1;AES256
38343931623631393237663863316161303432616665333637363034353938383135313461353461
6338393132333637333531613036643939366531343231610a373434353738353663653732313364
38643366366438303239393761383538613662626361653564363233386331663835393266313435
3632333734643135610a656538616239363265623330366165636166353363633561323039316261
34316132636164336561626562353234386363326332363861313438336638346365326262643463
3962363232386365323765653430663366623637326261323330
