- name: install fish repo (centos)
  become: true
  when: ansible_os_family == "CentOS" or ansible_distribution == "Amazon" and ansible_distribution_version == "2"
  shell: "cd /etc/yum.repos.d/ && \
    wget https://download.opensuse.org/repositories/shells:fish:release:3/CentOS_8/shells:fish:release:3.repo"
- name: install fish
  become: true
  package:
    name: fish
- name: set fish as the default shell for root
  when: use_fish
  become: true
  user:
    name: root
    shell: /usr/bin/fish
- name: set fish as the default shell for "{{ target_user }}"
  when: use_fish
  become: true
  user:
    name: "{{ target_user }}"
    shell: /usr/bin/fish
