version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ec2-instance-restart-frontend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1m3ncqlcvoj7u"
s3_prefix = "ec2-instance-restart-frontend"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
