# https://phyks.me/2014/11/getting-ipv6-to-work-with-a-kimsufi-server.html
# https://docs.ovh.com/gb/en/dedicated/network-ipv6/
- name: copy interfaces file
  become: true
  copy:
    src: 100-ipv6
    dest: /etc/network/interfaces.d/100-ipv6
    owner: root
    group: root
    mode: "644"
- name: disable ipv6 autoconf
  become: true
  lineinfile:
    path: /etc/sysctl.conf
    regexp: "^net.ipv6.conf.all.autoconf="
    line: net.ipv6.conf.all.autoconf=0
- name: disable ipv6 accept_ra
  become: true
  lineinfile:
    path: /etc/sysctl.conf
    regexp: "^net.ipv6.conf.all.accept_ra="
    line: net.ipv6.conf.all.accept_ra=0
- name: restart eno1 network interface
  become: true
  shell:
    cmd: "ifdown eno1 && ifup eno1"
- name: "Reset connection"
  meta: reset_connection
