$ANSIBLE_VAULT;1.1;AES256
35313536373866636135333631373839666438343835383533306430363832356536376661656631
3931663639366430393266346463343665663634313535340a376638316437363665653035316361
39666461643535663130313434313634333164623832363633373433653939636566323665343930
3065646139653966620a343933343734326332386330346435323436326265663539326335333435
30393463656235346166616336623162623135363939383037363166326164343633643064346133
66343830366665636331383430613937623039343565306638303130663035373634626564356132
63653262303239656533363338396533396535383165663938376239336130326238383339343431
39636562373937616639316633656632663535643562333532376261323063366534643664656633
33373163626135313464393132303530343238663833353138316532373636363637633763663661
37363663346333363665303030623736626135643635333730396664663435643761366264303065
37643366356339623465323739643838303532306536656636326138653164636536646235623935
37313137363734346632373939643831613230306336653738653362303466393361373335363037
3961
