[package]
name = "jukebox"
version = "0.1.0"
edition = "2021"

[dependencies]
# pcsc = "2.6.0"
sonos = "0.1.4"
rspotify = { version = "0.11.3", features = ["cli"] }
toml = "0.7.4"
serde = "1.0.133"
tokio = { version = "1", features = ["full"] }
