version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cashly-web"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1m3ncqlcvoj7u"
s3_prefix = "cashly-web"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"

